### ISSUE TITLE
exception during execution

### ISSUE THREAD

**Issue by louking** [pallets/flask-ext-migrate#27]
I tried this for https://github.com/louking/rrwebapp/releases/tag/2.6.0 and witnessed the following exception. No files had been changed.

    (rrwebapp) C:\Users\Lou\Documents\Lou's Software\projects\rrwebapp>flask_ext_migrate rrwebapp
    Traceback (most recent call last):
      File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "C:\Python27\Lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\Users\Lou\Documents\Lou's Software\projects\rrwebapp\rrwebapp\Scripts\flask_ext_migrate.exe\__main__.py", line 9, in <module>
      File "c:\users\lou\documents\lou's software\projects\rrwebapp\rrwebapp\lib\site-packages\click\core.py", line 716, in __call__
        return self.main(*args, **kwargs)
      File "c:\users\lou\documents\lou's software\projects\rrwebapp\rrwebapp\lib\site-packages\click\core.py", line 696, in main
        rv = self.invoke(ctx)
      File "c:\users\lou\documents\lou's software\projects\rrwebapp\rrwebapp\lib\site-packages\click\core.py", line 889, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "c:\users\lou\documents\lou's software\projects\rrwebapp\rrwebapp\lib\site-packages\click\core.py", line 534, in invoke
        return callback(*args, **kwargs)
      File "c:\users\lou\documents\lou's software\projects\rrwebapp\rrwebapp\lib\site-packages\flask_ext_migrate\startup.py", line 21, in startup
        fix(filepath)
      File "c:\users\lou\documents\lou's software\projects\rrwebapp\rrwebapp\lib\site-packages\flask_ext_migrate\__init__.py", line 142, in fix
        ast = fix_function_calls(ast)
      File "c:\users\lou\documents\lou's software\projects\rrwebapp\rrwebapp\lib\site-packages\flask_ext_migrate\__init__.py", line 106, in fix_function_calls
        if (node.value[0].value == 'flask' and
      File "c:\users\lou\documents\lou's software\projects\rrwebapp\rrwebapp\lib\site-packages\redbaron\base_nodes.py", line 691, in __getattr__
        self.__class__.__name__, key, key))
    AttributeError: ListComprehensionNode instance has no attribute 'value' and 'value' is not a valid identifier of another node

**Comment by louking** [comment]
Tried again, running this one level down at https://github.com/louking/rrwebapp/tree/master/rrwebapp level. This time files were changed, but still got the same exception.

**Comment by keyan** [comment]
Hi @louking thanks for opening this issue! I'll take a look this week and try to triage it.

**Comment by patrickyan** [comment]
Getting the same exact error.

**Comment by keyan** [comment]
Sorry for neglecting this for so long. It looks like this commit might be to blame https://github.com/PyCQA/redbaron/commit/7de730dc19326e12a6c50ad175435f835a30b99e.

I will pin the baron/redbaron versions and release a new version.

Thanks!
