### ISSUE TITLE
TypeError: check_user_input() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by sibelius** [pallets/flask-ext-migrate#4]
I'm trying to run the flask_ext_migrate like this:

`flask_ext_migrate app.py`

but I'm receiving an error like that:

``` python
Traceback (most recent call last):
  File "app/bin/flask_ext_migrate", line 11, in <module>
    sys.exit(startup())
  File "app/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "app/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "app/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "app/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File ".virtualenvs/app/lib/python3.4/site-packages/flask_ext_migrate/startup.py", line 9, in startup
    fix(input_file)
  File ".virtualenvs/app/lib/python3.4/site-packages/flask_ext_migrate/__init__.py", line 153, in fix
    check_user_input(input_file)
TypeError: check_user_input() takes 0 positional arguments but 1 was given
```

**Comment by untitaker** [comment]
Fixed in #5
