### ISSUE TITLE
check_user_input() takes no arguments (1 given)

### ISSUE THREAD

**Issue by ar-anvd** [pallets/flask-ext-migrate#6]
Just for debug, demo.py is an empty file

`flask_ext_migrate demo.py`

```
Traceback (most recent call last):
  File "/home/vagrant/myproject/venv/bin/flask_ext_migrate", line 9, in <module>
    load_entry_point('flask-ext-migrate==0.0.1', 'console_scripts', 'flask_ext_migrate')()
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask_ext_migrate/startup.py", line 9, in startup
    fix(input_file)
  File "/home/vagrant/myproject/venv/local/lib/python2.7/site-packages/flask_ext_migrate/__init__.py", line 153, in fix
    check_user_input(input_file)
TypeError: check_user_input() takes no arguments (1 given)

```

**Comment by davidism** [comment]
#5
